name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6
    - name: Block Fixup/Squash Merge
      uses: acolombier/block-fixup-merge-action@master
